# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llms.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nllms.proto\"\x0f\n\rEmptyWithLlms\"7\n\x13HealthCheckResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x11UploadFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\x0c\"6\n\x12UploadFileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x9b\x01\n\x12\x43hatMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x33\n\x08metadata\x18\x02 \x03(\x0b\x32!.ChatMessageRequest.MetadataEntry\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"7\n\x13\x43hatMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xac\x01\n\x04llms\x12\x35\n\nUploadFile\x12\x12.UploadFileRequest\x1a\x13.UploadFileResponse\x12\x38\n\x0bSendMessage\x12\x13.ChatMessageRequest\x1a\x14.ChatMessageResponse\x12\x33\n\x0bHealthCheck\x12\x0e.EmptyWithLlms\x1a\x14.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGEREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_CHATMESSAGEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EMPTYWITHLLMS']._serialized_start=14
  _globals['_EMPTYWITHLLMS']._serialized_end=29
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=31
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=86
  _globals['_UPLOADFILEREQUEST']._serialized_start=88
  _globals['_UPLOADFILEREQUEST']._serialized_end=147
  _globals['_UPLOADFILERESPONSE']._serialized_start=149
  _globals['_UPLOADFILERESPONSE']._serialized_end=203
  _globals['_CHATMESSAGEREQUEST']._serialized_start=206
  _globals['_CHATMESSAGEREQUEST']._serialized_end=361
  _globals['_CHATMESSAGEREQUEST_METADATAENTRY']._serialized_start=314
  _globals['_CHATMESSAGEREQUEST_METADATAENTRY']._serialized_end=361
  _globals['_CHATMESSAGERESPONSE']._serialized_start=363
  _globals['_CHATMESSAGERESPONSE']._serialized_end=418
  _globals['_LLMS']._serialized_start=421
  _globals['_LLMS']._serialized_end=593
# @@protoc_insertion_point(module_scope)
